<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="LAPTOP-NFPKR2Q3" name="TestDemos.TestNGFailedRetryDemo" tests="6" failures="1" timestamp="2022-03-26T15:04:54 IST" time="0.091" errors="0">
  <testcase name="test16" time="0.012" classname="TestDemos.TestNGFailedRetryDemo">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertTrue(Assert.java:31)
at TestDemos.TestNGFailedRetryDemo.test16(TestNGFailedRetryDemo.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- test16 -->
  <system-out/>
  <testcase name="test16" time="0.028" classname="TestDemos.TestNGFailedRetryDemo">
    <skipped/>
  </testcase> <!-- test16 -->
  <system-out/>
  <testcase name="test16" time="0.015" classname="TestDemos.TestNGFailedRetryDemo">
    <skipped/>
  </testcase> <!-- test16 -->
  <system-out/>
  <testcase name="test15" time="0.004" classname="TestDemos.TestNGFailedRetryDemo"/>
  <system-out/>
  <testcase name="test16" time="0.002" classname="TestDemos.TestNGFailedRetryDemo">
    <skipped/>
  </testcase> <!-- test16 -->
  <system-out/>
  <testcase name="test14" time="0.030" classname="TestDemos.TestNGFailedRetryDemo"/>
  <system-out/>
</testsuite> <!-- TestDemos.TestNGFailedRetryDemo -->
