<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-NFPKR2Q3" ignored="1" name="Default test(failed)" tests="2" failures="1" timestamp="2022-03-26T14:57:28 IST" time="0.483" errors="0">
  <testcase name="test16" time="0.04" classname="TestDemos.TestNGFailedRetryDemo">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertTrue(Assert.java:31)
at TestDemos.TestNGFailedRetryDemo.test16(TestNGFailedRetryDemo.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test16 -->
  <testcase name="test15" time="0.003" classname="TestDemos.TestNGFailedRetryDemo"/>
  <testcase name="test14" time="0.0" classname="TestDemos.TestNGFailedRetryDemo">
    <ignored/>
  </testcase> <!-- test14 -->
</testsuite> <!-- Default test(failed) -->
